/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

// ============ ADD THESE IMPORTS ============
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
// ===========================================


/**
 *
 * @author anubhavsilwal
 */
public class AssetDistributionChartFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AssetDistributionChartFrame.class.getName());

    /**
     * Creates new form AssetDistributionChartFrame
     */
    
    // ============ ADD THIS VARIABLE ============
    private ChartPanel chartPanel;
    // ===========================================

    
    public AssetDistributionChartFrame() {
        initComponents();
        createPieChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 280));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // ============ ADD ALL THESE CUSTOM METHODS HERE ============
    
    private void createPieChart() {
        try {
            // 1. Create dataset for pie chart
            DefaultPieDataset dataset = getChartData();
            
            // 2. Create pie chart
            JFreeChart pieChart = ChartFactory.createPieChart(
                "Asset Distribution",      // Chart title
                dataset,                   // Data
                true,                      // Show legend
                true,                      // Use tooltips
                false                      // Configure URLs
            );
            
            // 3. Customize chart
            customizeChart(pieChart);
            
            // 4. Create chart panel
            chartPanel = new ChartPanel(pieChart);
            chartPanel.setPreferredSize(new java.awt.Dimension(400, 260));
            
            // 5. Add to frame
            if (getContentPane() != null) {
                getContentPane().removeAll();
                getContentPane().setLayout(new java.awt.BorderLayout());
                getContentPane().add(chartPanel, java.awt.BorderLayout.CENTER);
            }
            
            // 6. Refresh
            revalidate();
            repaint();
            
        } catch (Exception e) {
            System.out.println("Pie chart error: " + e.getMessage());
            showErrorMessage();
        }
    }
    
    private DefaultPieDataset getChartData() {
        DefaultPieDataset dataset = new DefaultPieDataset();
        
        // Sample asset distribution data
        dataset.setValue("Cash", 25000);
        dataset.setValue("Stocks", 45000);
        dataset.setValue("Bonds", 18000);
        dataset.setValue("Real Estate", 35000);
        dataset.setValue("Retirement Funds", 42000);
        dataset.setValue("Other Assets", 12000);
        
        return dataset;
    }
    
    private void customizeChart(JFreeChart chart) {
        // Set title style
        chart.getTitle().setFont(new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 14));
        chart.getTitle().setPaint(new Color(51, 51, 51));
        
        // Get the plot
        PiePlot plot = (PiePlot) chart.getPlot();
        
        // Set background color
        chart.setBackgroundPaint(Color.WHITE);
        plot.setBackgroundPaint(Color.WHITE);
        
        // Set section colors (various colors for different assets)
        plot.setSectionPaint("Cash", new Color(76, 175, 80));        // Green
        plot.setSectionPaint("Stocks", new Color(33, 150, 243));     // Blue
        plot.setSectionPaint("Bonds", new Color(156, 39, 176));      // Purple
        plot.setSectionPaint("Real Estate", new Color(255, 152, 0)); // Orange
        plot.setSectionPaint("Retirement Funds", new Color(244, 67, 54)); // Red
        plot.setSectionPaint("Other Assets", new Color(121, 85, 72)); // Brown
        
        // Show percentages on chart
        plot.setLabelGenerator(new StandardPieSectionLabelGenerator("{0}: {1} ({2})"));
        plot.setLabelFont(new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 11));
        plot.setLabelPaint(new Color(51, 51, 51));
        
        // Set section outline
        plot.setSectionOutlinePaint(Color.WHITE);
        plot.setSectionOutlineStroke(new java.awt.BasicStroke(1.5f));
        
        // Set legend font
        chart.getLegend().setItemFont(new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 11));
    }
    
    private void showErrorMessage() {
        javax.swing.JLabel errorLabel = new javax.swing.JLabel(
            "Asset Distribution Chart",
            javax.swing.SwingConstants.CENTER
        );
        errorLabel.setFont(new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 14));
        errorLabel.setForeground(new Color(102, 102, 102));
        
        if (getContentPane() != null) {
            getContentPane().removeAll();
            getContentPane().setLayout(new java.awt.BorderLayout());
            getContentPane().add(errorLabel, java.awt.BorderLayout.CENTER);
            revalidate();
            repaint();
        }
    }
    
    // Method to get the chart panel for embedding in dashboard
    public JPanel getChartPanel() {
        if (chartPanel == null) {
            createPieChart();
        }
        return chartPanel;
    }
    
    // Method to refresh the chart (for future use)
    public void refreshChart() {
        createPieChart();
    }
    
    // ============ END OF CUSTOM METHODS ============
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AssetDistributionChartFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
