/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author samee
 */
public class cardspanel extends javax.swing.JPanel {

    /**
     * Creates new form cardspanel
     */
    public cardspanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemname = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        value = new javax.swing.JLabel();
        editbtn = new javax.swing.JButton();
        removebtn = new javax.swing.JButton();
        price = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(280, 250));
        setLayout(null);

        itemname.setText("item name");
        add(itemname);
        itemname.setBounds(10, 140, 100, 16);

        category.setText("category");
        add(category);
        category.setBounds(10, 160, 70, 20);

        value.setText("value");
        add(value);
        value.setBounds(10, 190, 28, 20);

        editbtn.setText("edit");
        editbtn.addActionListener(this::editbtnActionPerformed);
        add(editbtn);
        editbtn.setBounds(10, 230, 72, 23);

        removebtn.setText("remove");
        add(removebtn);
        removebtn.setBounds(150, 230, 72, 23);

        price.setText("price");
        add(price);
        price.setBounds(160, 190, 60, 16);
        add(jLabel5);
        jLabel5.setBounds(30, 20, 180, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel category;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel itemname;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel price;
    private javax.swing.JButton removebtn;
    private javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables
}
