/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author samee
 */
public class ExpensePiePanel extends javax.swing.JPanel {

    /**
     * Creates new form BarChartPanel
     */
    public ExpensePiePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlchartcontainer = new javax.swing.JPanel();
        lbltitle = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnlchartcontainer.setBackground(new java.awt.Color(204, 255, 153));
        pnlchartcontainer.setLayout(null);

        lbltitle.setText("income vs expenses");
        pnlchartcontainer.add(lbltitle);
        lbltitle.setBounds(50, 10, 160, 16);

        add(pnlchartcontainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbltitle;
    private javax.swing.JPanel pnlchartcontainer;
    // End of variables declaration//GEN-END:variables
public JPanel getChartContainer() { return pnlchartcontainer; }
public JLabel getTitleLabel() { return lbltitle; }
}
