/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author salmanansari.81
 */
public class forgotPassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(forgotPassword.class.getName());

    /**
     * Creates new form forgotPassword
     */
    public forgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        sendButton = new javax.swing.JButton();
        OTPFILL = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(205, 231, 217));
        jPanel3.setPreferredSize(new java.awt.Dimension(1440, 900));
        jPanel3.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(167, 230, 195));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(167, 230, 195));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setSize(new java.awt.Dimension(100, 84));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 100, 84);

        jLabel2.setFont(new java.awt.Font("Kohinoor Gujarati", 1, 24)); // NOI18N
        jLabel2.setText("Reset Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 250, 230, 40);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("Conform New Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 390, 180, 18);

        jButton1.setText(" ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 410, 350, 30);

        submitButton.setBackground(new java.awt.Color(64, 169, 29));
        submitButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton);
        submitButton.setBounds(170, 470, 150, 30);

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel11.setText("New Password");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(70, 320, 130, 18);

        jButton5.setText(" ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(70, 340, 350, 30);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(730, 170, 480, 610);

        jPanel4.setBackground(new java.awt.Color(167, 230, 195));
        jPanel4.setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel6.setText("jLabel1");
        jLabel6.setSize(new java.awt.Dimension(100, 84));
        jPanel4.add(jLabel6);
        jLabel6.setBounds(190, 100, 100, 84);

        jLabel7.setFont(new java.awt.Font("Kohinoor Gujarati", 1, 24)); // NOI18N
        jLabel7.setText("Forgot Password");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(150, 250, 230, 40);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel8.setText("Provide us your account email or cell number and we'll send ");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(40, 280, 450, 40);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        jLabel9.setText("OTP code on your email to reset the password");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(40, 300, 340, 30);

        jLabel10.setText("Enter OTP code");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(60, 480, 130, 17);

        jButton3.setText(" ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(60, 390, 350, 30);

        sendButton.setBackground(new java.awt.Color(64, 169, 29));
        sendButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        sendButton.setText("send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        jPanel4.add(sendButton);
        sendButton.setBounds(160, 440, 150, 30);

        OTPFILL.setText(" ");
        OTPFILL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OTPFILLActionPerformed(evt);
            }
        });
        jPanel4.add(OTPFILL);
        OTPFILL.setBounds(60, 500, 360, 30);

        jButton2.setBackground(new java.awt.Color(64, 169, 29));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton2.setText("ok");
        jPanel4.add(jButton2);
        jButton2.setBounds(160, 540, 150, 30);

        jLabel12.setText("Enter email or cell number");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(60, 370, 170, 17);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(130, 170, 480, 610);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1580, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void OTPFILLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OTPFILLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OTPFILLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new forgotPassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField OTPFILL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
