/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

// ============ ADD THESE IMPORTS ============
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
// ===========================================

/**
 *
 * @author anubhavsilwal
 */
public class IncomeExpenseChartFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IncomeExpenseChartFrame.class.getName());
    
     // ============ ADD THIS VARIABLE ============
    private ChartPanel chartPanel;
    // ===========================================
    
    /**
     * Creates new form IncomeExpenseChartFrame
     */
    public IncomeExpenseChartFrame() {
        initComponents();
        createBarChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(440, 280));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IncomeExpenseChartFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
// ============ ADD ALL THESE METHODS HERE ============
    
    private void createBarChart() {
        try {
            // 1. Create dataset
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            
            // Sample data for 6 months
            // Income data
            dataset.addValue(5200, "Income", "Jan");
            dataset.addValue(5500, "Income", "Feb");
            dataset.addValue(5300, "Income", "Mar");
            dataset.addValue(5800, "Income", "Apr");
            dataset.addValue(6000, "Income", "May");
            dataset.addValue(6200, "Income", "Jun");
            
            // Expense data
            dataset.addValue(1800, "Expense", "Jan");
            dataset.addValue(2100, "Expense", "Feb");
            dataset.addValue(1900, "Expense", "Mar");
            dataset.addValue(2200, "Expense", "Apr");
            dataset.addValue(2400, "Expense", "May");
            dataset.addValue(2600, "Expense", "Jun");
            
            // 2. Create bar chart
            JFreeChart barChart = ChartFactory.createBarChart(
                "Income vs Expense - Last 6 Months",
                "Month",
                "Amount ($)",
                dataset,
                PlotOrientation.VERTICAL,
                true,    // Show legend
                true,    // Use tooltips
                false    // Configure URLs
            );
            
            // 3. Customize chart
            customizeChart(barChart);
            
            // 4. Create chart panel
            chartPanel = new ChartPanel(barChart);
            chartPanel.setPreferredSize(new java.awt.Dimension(420, 250));
            
            // 5. Add to frame
            if (getContentPane() != null) {
                getContentPane().removeAll();
                getContentPane().setLayout(new java.awt.BorderLayout());
                getContentPane().add(chartPanel, java.awt.BorderLayout.CENTER);
            }
            
            // 6. Refresh
            revalidate();
            repaint();
            
        } catch (Exception e) {
            System.out.println("Bar chart error: " + e.getMessage());
            showErrorMessage();
        }
    }
    
    private void customizeChart(JFreeChart chart) {
        // Set title style
        chart.getTitle().setFont(new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 14));
        chart.getTitle().setPaint(new Color(51, 51, 51));
        
        // Get the plot
        CategoryPlot plot = chart.getCategoryPlot();
        
        // Set background colors
        chart.setBackgroundPaint(Color.WHITE);
        plot.setBackgroundPaint(Color.WHITE);
        
        // Set axis label colors
        plot.getDomainAxis().setTickLabelPaint(new Color(102, 102, 102));
        plot.getRangeAxis().setTickLabelPaint(new Color(102, 102, 102));
        
        // Customize bar colors
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, new Color(76, 175, 80));  // Green for Income
        renderer.setSeriesPaint(1, new Color(244, 67, 54));  // Red for Expense
        
        // Add some spacing between bars
        renderer.setItemMargin(0.2);
    }
    
    private void showErrorMessage() {
        javax.swing.JLabel errorLabel = new javax.swing.JLabel(
            "Income vs Expense Chart",
            javax.swing.SwingConstants.CENTER
        );
        errorLabel.setFont(new java.awt.Font("Helvetica Neue", java.awt.Font.PLAIN, 14));
        errorLabel.setForeground(new Color(102, 102, 102));
        
        if (getContentPane() != null) {
            getContentPane().removeAll();
            getContentPane().setLayout(new java.awt.BorderLayout());
            getContentPane().add(errorLabel, java.awt.BorderLayout.CENTER);
            revalidate();
            repaint();
        }
    }
    
    // Method to get the chart panel for embedding in dashboard
    public JPanel getChartPanel() {
        if (chartPanel == null) {
            createBarChart();
        }
        return chartPanel;
    }
    
    // ============ END OF CUSTOM METHODS ============
}
