/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.GridLayout;
import javax.swing.*;
import java.awt.event.ActionListener;

/**
 *
 * @author anubhavsilwal
 */
public class inventory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(inventory.class.getName());

    /**
     * Creates new form inventory
     */
    public inventory() {
        initComponents();
        setTitle("Inventory Management System");
        setSize(1300, 900);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true); 
        
        
    
        System.out.println("DEBUG: Window created, visible=" + isVisible());
       
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerpanel = new javax.swing.JPanel();
        appicon = new javax.swing.JLabel();
        backgorund = new javax.swing.JPanel();
        inventoryheader = new javax.swing.JLabel();
        centerpanel = new javax.swing.JPanel();
        youasssetstext = new javax.swing.JLabel();
        searchbar = new javax.swing.JTextField();
        additembtn = new javax.swing.JButton();
        onloan = new javax.swing.JPanel();
        text = new javax.swing.JLabel();
        onloanlabel = new javax.swing.JLabel();
        totalitems = new javax.swing.JPanel();
        text2 = new javax.swing.JLabel();
        totalitemslabel = new javax.swing.JLabel();
        totalvalue = new javax.swing.JPanel();
        text3 = new javax.swing.JLabel();
        totalvaluelabel = new javax.swing.JLabel();
        scrollpane = new javax.swing.JScrollPane();
        dashboardpanel = new javax.swing.JPanel();
        documentsbtn = new javax.swing.JButton();
        dashboardbtn = new javax.swing.JButton();
        inventorybtn = new javax.swing.JButton();
        lendingbtn = new javax.swing.JButton();
        goalsbtn = new javax.swing.JButton();
        financialbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        headerpanel.setBackground(new java.awt.Color(254, 251, 238));
        headerpanel.setLayout(null);

        appicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        headerpanel.add(appicon);
        appicon.setBounds(40, -60, 110, 220);

        backgorund.setBackground(new java.awt.Color(254, 251, 238));
        backgorund.setLayout(null);

        inventoryheader.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        inventoryheader.setText("My Inventory");
        inventoryheader.setAlignmentX(0.5F);
        inventoryheader.setPreferredSize(new java.awt.Dimension(300, 50));
        backgorund.add(inventoryheader);
        inventoryheader.setBounds(0, 10, 250, 40);

        headerpanel.add(backgorund);
        backgorund.setBounds(220, 50, 1230, 50);

        getContentPane().add(headerpanel);
        headerpanel.setBounds(-10, -10, 1450, 100);

        centerpanel.setBackground(new java.awt.Color(205, 231, 217));
        centerpanel.setLayout(null);

        youasssetstext.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        youasssetstext.setText("Your Assets");
        centerpanel.add(youasssetstext);
        youasssetstext.setBounds(30, 190, 150, 35);

        searchbar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        searchbar.setText("Search by name or category");
        searchbar.setAlignmentX(0.0F);
        searchbar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchbarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchbarFocusLost(evt);
            }
        });
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        centerpanel.add(searchbar);
        searchbar.setBounds(20, 30, 400, 40);
        searchbar.getAccessibleContext().setAccessibleDescription("");

        additembtn.setBackground(new java.awt.Color(93, 177, 132));
        additembtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        additembtn.setText("+      Add item");
        additembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additembtnActionPerformed(evt);
            }
        });
        centerpanel.add(additembtn);
        additembtn.setBounds(820, 40, 140, 40);

        onloan.setLayout(null);

        text.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text.setText("On Loan");
        onloan.add(text);
        text.setBounds(20, 10, 200, 25);

        onloanlabel.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        onloanlabel.setForeground(new java.awt.Color(225, 133, 0));
        onloanlabel.setText("3");
        onloan.add(onloanlabel);
        onloanlabel.setBounds(20, 40, 270, 40);

        centerpanel.add(onloan);
        onloan.setBounds(720, 100, 280, 90);

        totalitems.setLayout(null);

        text2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text2.setText("Total items");
        totalitems.add(text2);
        text2.setBounds(20, 10, 200, 25);

        totalitemslabel.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        totalitemslabel.setForeground(new java.awt.Color(17, 151, 31));
        totalitemslabel.setText("6");
        totalitems.add(totalitemslabel);
        totalitemslabel.setBounds(20, 40, 270, 40);

        centerpanel.add(totalitems);
        totalitems.setBounds(30, 100, 280, 90);

        totalvalue.setLayout(null);

        text3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        text3.setText("Total value");
        totalvalue.add(text3);
        text3.setBounds(10, 10, 200, 25);

        totalvaluelabel.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        totalvaluelabel.setForeground(new java.awt.Color(17, 151, 31));
        totalvaluelabel.setText("$20,000");
        totalvalue.add(totalvaluelabel);
        totalvaluelabel.setBounds(10, 40, 270, 40);

        centerpanel.add(totalvalue);
        totalvalue.setBounds(370, 100, 280, 90);

        scrollpane.setBackground(new java.awt.Color(255, 255, 255));
        scrollpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollpane.setViewportView(null);
        centerpanel.add(scrollpane);
        scrollpane.setBounds(30, 230, 970, 340);

        getContentPane().add(centerpanel);
        centerpanel.setBounds(210, 90, 1240, 800);

        dashboardpanel.setBackground(new java.awt.Color(224, 236, 229));
        dashboardpanel.setLayout(null);

        documentsbtn.setBackground(new java.awt.Color(255, 220, 169));
        documentsbtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        documentsbtn.setText("Documents");
        documentsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentsbtnActionPerformed(evt);
            }
        });
        dashboardpanel.add(documentsbtn);
        documentsbtn.setBounds(0, 350, 200, 50);

        dashboardbtn.setBackground(new java.awt.Color(255, 220, 169));
        dashboardbtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dashboardbtn.setText("Dashboard");
        dashboardbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardbtnActionPerformed(evt);
            }
        });
        dashboardpanel.add(dashboardbtn);
        dashboardbtn.setBounds(0, 10, 200, 50);

        inventorybtn.setBackground(new java.awt.Color(93, 177, 132));
        inventorybtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        inventorybtn.setText("My Inventory");
        inventorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventorybtnActionPerformed(evt);
            }
        });
        dashboardpanel.add(inventorybtn);
        inventorybtn.setBounds(0, 70, 200, 50);

        lendingbtn.setBackground(new java.awt.Color(255, 220, 169));
        lendingbtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lendingbtn.setText("Lending");
        dashboardpanel.add(lendingbtn);
        lendingbtn.setBounds(0, 140, 200, 50);

        goalsbtn.setBackground(new java.awt.Color(255, 220, 169));
        goalsbtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        goalsbtn.setText("Goals");
        dashboardpanel.add(goalsbtn);
        goalsbtn.setBounds(0, 210, 200, 50);

        financialbtn.setBackground(new java.awt.Color(255, 220, 169));
        financialbtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        financialbtn.setText("Financial Analytics");
        dashboardpanel.add(financialbtn);
        financialbtn.setBounds(0, 280, 200, 50);

        getContentPane().add(dashboardpanel);
        dashboardpanel.setBounds(10, 90, 200, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void dashboardbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardbtnActionPerformed

    private void inventorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventorybtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inventorybtnActionPerformed

    private void additembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additembtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_additembtnActionPerformed

    private void documentsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentsbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentsbtnActionPerformed

    private void searchbarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchbarFocusGained
        if (searchbar.getText().equals("Search by name or category")) {
            searchbar.setText("");
        }
    }//GEN-LAST:event_searchbarFocusGained

    private void searchbarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchbarFocusLost
          if (searchbar.getText().isEmpty()) {
            searchbar.setText("Search by name or category");
        }
    }//GEN-LAST:event_searchbarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new inventory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton additembtn;
    private javax.swing.JLabel appicon;
    private javax.swing.JPanel backgorund;
    private javax.swing.JPanel centerpanel;
    private javax.swing.JButton dashboardbtn;
    private javax.swing.JPanel dashboardpanel;
    private javax.swing.JButton documentsbtn;
    private javax.swing.JButton financialbtn;
    private javax.swing.JButton goalsbtn;
    private javax.swing.JPanel headerpanel;
    private javax.swing.JButton inventorybtn;
    private javax.swing.JLabel inventoryheader;
    private javax.swing.JButton lendingbtn;
    private javax.swing.JPanel onloan;
    private javax.swing.JLabel onloanlabel;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JTextField searchbar;
    private javax.swing.JLabel text;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JPanel totalitems;
    private javax.swing.JLabel totalitemslabel;
    private javax.swing.JPanel totalvalue;
    private javax.swing.JLabel totalvaluelabel;
    private javax.swing.JLabel youasssetstext;
    // End of variables declaration//GEN-END:variables

    public void setAddItemListener(ActionListener listener) {
        additembtn.addActionListener(listener);
    }
    
    public void setSearchListener(ActionListener listener) {
        searchbar.addActionListener(listener);
    }
    
    public void setDashboardListener(ActionListener listener) {
        dashboardbtn.addActionListener(listener);
    }
    
    public void setInventoryListener(ActionListener listener) {
        inventorybtn.addActionListener(listener);
    }
    
    public void setDocumentsListener(ActionListener listener) {
        documentsbtn.addActionListener(listener);
    }
    
    public void setLendingListener(ActionListener listener) {
        lendingbtn.addActionListener(listener);
    }
    
    public void setGoalsListener(ActionListener listener) {
        goalsbtn.addActionListener(listener);
    }
    
    public void setFinancialListener(ActionListener listener) {
        financialbtn.addActionListener(listener);
    }  
    
    public JButton getAddItemButton() {
        return additembtn;
    }
    
    public JTextField getSearchField() {
        return searchbar;
    }
    
    public JLabel getTotalItemsLabel() {
        return totalitemslabel;
    }
    
    public JLabel getTotalValueLabel() {
        return totalvaluelabel;
    }
    
    public JLabel getOnLoanLabel() {
        return onloanlabel;
    }
    
    public JScrollPane getItemsScrollPane() {
        return scrollpane;
    }
   

}