/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author salmanansari.81
 */
public class loanIDpanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loanIDpanel.class.getName());

    /**
     */
    public loanIDpanel() {
        initComponents();
    }

    
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        update1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        conformButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel17.setBackground(new java.awt.Color(224, 243, 235));
        jPanel17.setLayout(null);

        jLabel47.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel47.setText("UName");
        jPanel17.add(jLabel47);
        jLabel47.setBounds(22, 8, 61, 23);

        jLabel48.setText("Item:  ");
        jPanel17.add(jLabel48);
        jLabel48.setBounds(22, 45, 50, 17);

        jLabel49.setText("Due:  ");
        jPanel17.add(jLabel49);
        jLabel49.setBounds(22, 68, 35, 17);

        update1.setBackground(new java.awt.Color(30, 142, 97));
        update1.setForeground(new java.awt.Color(242, 242, 242));
        update1.setText("Update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        jPanel17.add(update1);
        update1.setBounds(870, 60, 129, 48);

        jTextField1.setText(" ");
        jPanel17.add(jTextField1);
        jTextField1.setBounds(60, 70, 160, 23);

        jTextField2.setText(" ");
        jPanel17.add(jTextField2);
        jTextField2.setBounds(60, 40, 160, 23);

        jLabel55.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel55.setText("$ xxx");
        jPanel17.add(jLabel55);
        jLabel55.setBounds(870, 30, 102, 25);

        conformButton1.setBackground(new java.awt.Color(51, 255, 51));
        conformButton1.setText("Confirn");
        conformButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conformButton1ActionPerformed(evt);
            }
        });
        jPanel17.add(conformButton1);
        conformButton1.setBounds(480, 110, 72, 23);

        getContentPane().add(jPanel17);
        jPanel17.setBounds(0, 30, 1040, 140);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update1ActionPerformed

    private void conformButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conformButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conformButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new loanIDpanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conformButton1;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
