/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.*;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author anubhavsilwal
 */
public class NetWorthChartFrame extends javax.swing.JFrame {
    
    private ChartPanel chartPanel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NetWorthChartFrame.class.getName());

    // Constructor - add code here
    public NetWorthChartFrame() {
        initComponents();  // This is auto-generated - DON'T TOUCH
        createChart();     // Add this line
    }
    
    private void createChart() {
        try {
            // 1. Create dataset
            DefaultCategoryDataset dataset = getChartData();
            
            // 2. Create chart
            JFreeChart lineChart = ChartFactory.createLineChart(
                "Net Worth Overview - Last 6 Months",
                "Month",
                "Net Worth ($)",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
            );
            
            // 3. Customize chart appearance
            lineChart.getCategoryPlot().getRenderer().setSeriesPaint(0, 
                new java.awt.Color(44, 102, 232));
            
            // 4. Create chart panel
            chartPanel = new ChartPanel(lineChart);
            chartPanel.setPreferredSize(new java.awt.Dimension(680, 380));
            
            // 5. Add to the frame (make sure contentPane exists)
            if (getContentPane() != null) {
                getContentPane().removeAll();  // Clear existing components
                getContentPane().setLayout(new java.awt.BorderLayout());
                getContentPane().add(chartPanel, java.awt.BorderLayout.CENTER);
            }
            
            // 6. Refresh the display
            revalidate();
            repaint();
            
        } catch (Exception e) {
            System.out.println("Chart creation error: " + e.getMessage());
            showErrorMessage();
        }
    }
    
    // Method to get data (using sample data for now)
    private DefaultCategoryDataset getChartData() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        // Sample data - we'll add database later
        dataset.addValue(45000, "Net Worth", "Jan");
        dataset.addValue(47000, "Net Worth", "Feb");
        dataset.addValue(46500, "Net Worth", "Mar");
        dataset.addValue(49000, "Net Worth", "Apr");
        dataset.addValue(51000, "Net Worth", "May");
        dataset.addValue(53000, "Net Worth", "Jun");
        
        return dataset;
    }
    
    // Fallback method
    private void showErrorMessage() {
        javax.swing.JLabel errorLabel = new javax.swing.JLabel(
            "Chart could not be loaded. Using sample data.",
            javax.swing.SwingConstants.CENTER
        );
        
        if (getContentPane() != null) {
            getContentPane().removeAll();
            getContentPane().setLayout(new java.awt.BorderLayout());
            getContentPane().add(errorLabel, java.awt.BorderLayout.CENTER);
            revalidate();
            repaint();
        }
    }
    
    // Method to get just the chart panel (for embedding in dashboard)
    public JPanel getChartPanel() {
        if (chartPanel == null) {
            createChart();
        }
        return chartPanel;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 410));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NetWorthChartFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
