/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.Record;

/**
 *
 * @author salmanansari.81
 */
public class RecordCard extends javax.swing.JPanel {

    /**
     * Creates new form RecordCard
     */
    public RecordCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        item = new javax.swing.JLabel();
        duedate = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();

        setBackground(new java.awt.Color(205, 231, 217));
        setLayout(null);

        username.setText("UserName:");
        add(username);
        username.setBounds(20, 10, 70, 20);

        item.setText("Item:");
        add(item);
        item.setBounds(20, 50, 29, 17);

        duedate.setText("DueDate:");
        add(duedate);
        duedate.setBounds(20, 90, 70, 17);

        amount.setText("Amount");
        add(amount);
        amount.setBounds(850, 90, 60, 20);
    }// </editor-fold>//GEN-END:initComponents
                                            

    // Method to set record data using Record object
    public void setRecord(Record record) {
        if (record != null) {
            usernameTextField.setText(record.getRecordUserName());
            itemTextField.setText(record.getRecordItem());
            duedateTextField.setText(record.getRecordDueDate());
            amountTextField.setText(String.format("$%.2f", record.getRecordAmount()));
            
            // Update labels
            username.setText("User: " + record.getRecordUserName());
            item.setText("Item: " + record.getRecordItem());
            duedate.setText("Due: " + record.getRecordDueDate());
            amount.setText("$" + String.format("%.2f", record.getRecordAmount()));
        }
    }
    
    // Method to set record data using individual parameters
    public void setRecordData(String userName, String itemName, String dueDate, double amountValue) {
        usernameTextField.setText(userName);
        itemTextField.setText(itemName);
        duedateTextField.setText(dueDate);
        amountTextField.setText(String.format("$%.2f", amountValue));
        
        // Update labels
        username.setText("User: " + userName);
        item.setText("Item: " + itemName);
        duedate.setText("Due: " + dueDate);
        amount.setText("$" + String.format("%.2f", amountValue));
    }
    
    // Getters for the text fields (optional, if you need to retrieve data)
    public String getBorrowerName() {
        return usernameTextField.getText();
    }
    
    public String getItemName() {
        return itemTextField.getText();
    }
    
    public String getDueDate() {
        return duedateTextField.getText();
    }
    
    public String getAmount() {
        return amountTextField.getText();
    }
    
    // Clear all fields
    public void clearFields() {
        usernameTextField.setText("");
        itemTextField.setText("");
        duedateTextField.setText("");
        amountTextField.setText("");
        
        username.setText("UserName:");
        item.setText("Item:");
        duedate.setText("DueDate:");
        amount.setText("Amount:");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JLabel duedate;
    private javax.swing.JLabel item;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

}