/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.Record;
import javax.swing.JOptionPane;
import model.Loan;
import java.awt.*;

/**
 *
 * @author salmanansari.81
 */
public class RecordCard extends javax.swing.JPanel {
     
    private lending parentFrame;
    private final Loan loan;

    /**
     * Creates new form RecordCard
     */
    public RecordCard(Loan loan, lending parentFrame) {
        this.loan = loan;
        this.parentFrame = parentFrame;
        initComponents();
        updateDisplay();
        
        updatebtn.addActionListener(evt -> updatebtnActionPerformed(evt));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        item = new javax.swing.JLabel();
        duedate = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(205, 231, 217));
        setLayout(null);

        username.setText("UserName:");
        add(username);
        username.setBounds(20, 10, 390, 40);

        item.setText("Item:");
        add(item);
        item.setBounds(20, 50, 360, 30);

        duedate.setText("DueDate:");
        add(duedate);
        duedate.setBounds(20, 90, 360, 30);

        amount.setText("Amount");
        add(amount);
        amount.setBounds(980, 60, 60, 20);

        updatebtn.setBackground(new java.awt.Color(93, 177, 132));
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        add(updatebtn);
        updatebtn.setBounds(960, 80, 80, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatebtnActionPerformed
    
    

//    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {
//        // Open update dialog
//        if (parentFrame != null && parentFrame.getController() != null) {
//            parentFrame.getController().updateLoan(loan.getBorrowerName(), loan.getItemName());
//        }
//    }

    private void updateDisplay() {
        username.setText("Borrower: " + loan.getBorrowerName());
        item.setText("Item: " + loan.getItemName());
        duedate.setText("Due: " + loan.getDueDate());
        amount.setText("$" + String.format("%.2f", loan.getAmount()));
    }
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JLabel duedate;
    private javax.swing.JLabel item;
    private javax.swing.JButton updatebtn;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

}   

    
    
    
   
