/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.Record;
import javax.swing.JOptionPane;
import model.Loan;

/**
 *
 * @author salmanansari.81
 */
public class RecordCard extends javax.swing.JPanel {
     
    private lending parentFrame;
    private final Loan loan;

    /**
     * Creates new form RecordCard
     */
    public RecordCard(Loan loan, lending parentFrame) {
        this.loan = loan;
        this.parentFrame = parentFrame;
        initComponents();
        updateDisplay();
        
        updatebtn.addActionListener(evt -> updatebtnActionPerformed(evt));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JLabel();
        item = new javax.swing.JLabel();
        duedate = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(205, 231, 217));
        setLayout(null);

        username.setText("UserName:");
        add(username);
        username.setBounds(20, 10, 70, 20);

        item.setText("Item:");
        add(item);
        item.setBounds(20, 50, 29, 17);

        duedate.setText("DueDate:");
        add(duedate);
        duedate.setBounds(20, 90, 70, 17);

        amount.setText("Amount");
        add(amount);
        amount.setBounds(850, 70, 60, 20);

        updatebtn.setBackground(new java.awt.Color(93, 177, 132));
        updatebtn.setText("Update");
        add(updatebtn);
        updatebtn.setBounds(840, 90, 73, 23);
    }// </editor-fold>//GEN-END:initComponents
    
    

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {
        // Open update dialog
        if (parentFrame != null && parentFrame.getController() != null) {
            parentFrame.getController().updateLoan(loan.getBorrowerName(), loan.getItemName());
        }
    }

    private void updateDisplay() {
        username.setText("Borrower: " + loan.getBorrowerName());
        item.setText("Item: " + loan.getItemName());
        duedate.setText("Due: " + loan.getDueDate());
        amount.setText("$" + String.format("%.2f", loan.getAmount()));
    }
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JLabel duedate;
    private javax.swing.JLabel item;
    private javax.swing.JButton updatebtn;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

}   

    
    
    
   
