/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.JOptionPane;

/**
 *
 * @author salmanansari.81
 */
public class UpdateUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateUI.class.getName());

    /**
     * Creates new form UpdateUI
     */
    public UpdateUI() {
        initComponents();
    }
    
    // ADD THESE METHODS TO SET FORM DATA
    public void setItemText(String text) {
        item.setText(text);
    }
    
    public void setAmountText(String text) {
        amount.setText(text);
    }
    
    public void setDueText(String text) {
        due.setText(text);
    }
    
    public void setAllFields(String itemText, String amountText, String dueDate) {
        setItemText(itemText);
        setAmountText(amountText);
        setDueText(dueDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        item = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        due = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(205, 231, 217));
        jPanel2.setLayout(null);

        jLabel1.setText("Item:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 80, 80, 20);

        jLabel2.setText("Amount:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 180, 80, 20);

        item.setText(" ");
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActionPerformed(evt);
            }
        });
        jPanel2.add(item);
        item.setBounds(140, 80, 200, 23);

        amount.setText(" ");
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        jPanel2.add(amount);
        amount.setBounds(140, 180, 200, 23);

        jLabel4.setText("Due Date:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 130, 80, 20);

        due.setText(" ");
        due.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueActionPerformed(evt);
            }
        });
        jPanel2.add(due);
        due.setBounds(140, 130, 200, 23);

        confirm.setBackground(new java.awt.Color(0, 153, 0));
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel2.add(confirm);
        confirm.setBounds(160, 280, 80, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 400, 400);

        jPanel1.setBackground(new java.awt.Color(254, 251, 238));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActionPerformed
        // TODO add your handling code here:
        validateItemName();
    }//GEN-LAST:event_itemActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
        validateAmount();
    }//GEN-LAST:event_amountActionPerformed

    private void dueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueActionPerformed
        // TODO add your handling code here:
        validateDate();
    }//GEN-LAST:event_dueActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        createNewLoan();
    }//GEN-LAST:event_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    // IMPLEMENT THESE METHODS
    private void validateItemName() {
        if (item.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Item name cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
            item.requestFocus();
        }
    }
    
    private void validateAmount() {
        try {
            double amt = Double.parseDouble(amount.getText().trim());
            if (amt <= 0) {
                JOptionPane.showMessageDialog(this, "Amount must be greater than 0!", "Error", JOptionPane.ERROR_MESSAGE);
                amount.requestFocus();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid amount!", "Error", JOptionPane.ERROR_MESSAGE);
            amount.requestFocus();
        }
    }
    
    private void validateDate() {
        if (due.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Due date cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
            due.requestFocus();
        }
    }
    
    private void createNewLoan() {
        validateItemName();
        validateAmount();
        validateDate();
        
        if (!item.getText().trim().isEmpty() && 
            !amount.getText().trim().isEmpty() && 
            !due.getText().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, 
                "Update successful!\nItem: " + item.getText() + 
                "\nAmount: " + amount.getText() + 
                "\nDue Date: " + due.getText(), 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose(); // Close the form
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField due;
    private javax.swing.JTextField item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
