/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author salmanansari.81
 */
public class updateRecordUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(updateRecordUI.class.getName());

    /**
     * Creates new form updateRecordUI
     */
    public updateRecordUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        item = new javax.swing.JLabel();
        duedate = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        itemTextField = new javax.swing.JTextField();
        duedateTextField = new javax.swing.JTextField();
        amountTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 102));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(254, 251, 238));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 100);

        jPanel3.setBackground(new java.awt.Color(205, 231, 217));
        jPanel3.setLayout(null);

        item.setText("Item:");
        jPanel3.add(item);
        item.setBounds(30, 40, 29, 17);

        duedate.setText("DueDate:");
        jPanel3.add(duedate);
        duedate.setBounds(30, 80, 70, 17);

        amount.setText("Amount:");
        jPanel3.add(amount);
        amount.setBounds(30, 130, 70, 17);

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setText("Confirm");
        jPanel3.add(jButton1);
        jButton1.setBounds(130, 210, 75, 23);

        itemTextField.setText(" ");
        itemTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(itemTextField);
        itemTextField.setBounds(100, 40, 160, 23);

        duedateTextField.setText(" ");
        duedateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duedateTextFieldActionPerformed(evt);
            }
        });
        jPanel3.add(duedateTextField);
        duedateTextField.setBounds(100, 80, 160, 23);

        amountTextField.setText(" ");
        jPanel3.add(amountTextField);
        amountTextField.setBounds(100, 130, 160, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 100, 350, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemTextFieldActionPerformed

    private void duedateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duedateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duedateTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new updateRecordUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JLabel duedate;
    private javax.swing.JTextField duedateTextField;
    private javax.swing.JLabel item;
    private javax.swing.JTextField itemTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
